In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,LabelBinarizer,OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
cars=pd.read_csv('/content/cars.csv')
df=pd.read_csv('/content/customer (1).csv')

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,2:4],df.iloc[:,:-1],test_size=0.2)

In [5]:
X_train

review education
38     Good    School
43     Poor        PG
34  Average    School
11     Good        UG
36     Good        UG
18     Good    School
23     Good    School
40     Good    School
26     Poor        PG
7      Poor    School
8   Average        UG
49     Good        UG
37  Average        PG
17     Poor        UG
1      Poor        UG
31     Poor    School
42     Good        PG
24  Average        PG
10     Good        UG
48     Good        UG
16     Poor        UG
46     Poor        PG
25     Good    School
21  Average        PG
0   Average    School
2      Good        PG
29  Average        UG
47     Good        PG
15     Poor        UG
12     Poor    School
35     Poor    School
13  Average    School
32  Average        UG
28     Poor    School
4   Average        UG
41     Good        PG
20  Average    School
19     Poor        PG
39     Poor        PG
14     Poor        PG

In [6]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [7]:
X_train

review education
38     Good    School
43     Poor        PG
34  Average    School
11     Good        UG
36     Good        UG
18     Good    School
23     Good    School
40     Good    School
26     Poor        PG
7      Poor    School
8   Average        UG
49     Good        UG
37  Average        PG
17     Poor        UG
1      Poor        UG
31     Poor    School
42     Good        PG
24  Average        PG
10     Good        UG
48     Good        UG
16     Poor        UG
46     Poor        PG
25     Good    School
21  Average        PG
0   Average    School
2      Good        PG
29  Average        UG
47     Good        PG
15     Poor        UG
12     Poor    School
35     Poor    School
13  Average    School
32  Average        UG
28     Poor    School
4   Average        UG
41     Good        PG
20  Average    School
19     Poor        PG
39     Poor        PG
14     Poor        PG

In [8]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [10]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [11]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [12]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [13]:
# Handle Unknown value
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],handle_unknown='use_encoded_value',unknown_value=-1)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,2:4],df.iloc[::-1],test_size=0.2)

In [15]:
x_train=oe.fit(X_train)

In [16]:
oe.transform(np.array(['Luck','UG']).reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.,  1.]])

In [17]:
# Handeling Multiple categories
x=np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2],dtype=object).T
x

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [18]:
oe=OrdinalEncoder(max_categories=3)
oe.fit(x)

OrdinalEncoder(max_categories=3)

In [19]:
oe.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [20]:
oe.transform(np.array(['snake','horse','dog','cat']).reshape(4,1))

array([[2.],
       [2.],
       [2.],
       [0.]])

# Ordinal Encodeing- Used in input feature has order in  its value.

In [21]:
enc = OrdinalEncoder(min_frequency=4).fit(x)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [22]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

In [23]:
# Handeling missing value
data=[['cat'],[np.nan],['dog'],['fist']]
order=OrdinalEncoder(encoded_missing_value=-1)
dat=order.fit_transform(data)
print(dat)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]]


Label Encoder - Used in Dependent value

In [24]:
le=LabelEncoder()
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)


In [25]:
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [26]:
y_train

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [27]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [28]:
le.inverse_transform(np.array([0,1,0,1]))

array(['No', 'Yes', 'No', 'Yes'], dtype=object)

# One Hot Encoder- Only one bit is hot and True every time. Used in the Input Feature

In [29]:
cars.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [30]:
cars.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [31]:
X_train,X_test,y_train,y_test=train_test_split(cars.iloc[:,0:4:2],cars.iloc[:,-1],test_size=0.2)

In [32]:
ohe=OneHotEncoder(sparse_output=False, dtype=np.int32)

In [33]:
ohe.fit_transform(X_train)

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [34]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Peugeot',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [35]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [36]:
ohe.n_features_in_

2

In [37]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Peugeot', 'brand_Renault', 'brand_Skoda',
       'brand_Tata', 'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [38]:
pd.DataFrame(ohe.fit_transform(X_train),columns=ohe.get_feature_names_out())

brand_Ambassador  brand_Ashok  brand_Audi  brand_BMW  brand_Chevrolet  \
0                    0            0           0          0                0   
1                    0            0           0          0                0   
2                    0            0           0          0                0   
3                    0            0           0          0                0   
4                    0            0           0          0                0   
...                ...          ...         ...        ...              ...   
6497                 0            0           0          0                0   
6498                 0            0           0          0                0   
6499                 0            0           0          0                0   
6500                 0            0           0          0                0   
6501                 0            0           0          0                0   

      brand_Daewoo  brand_Datsun  brand_Fiat  brand_Force  brand_Ford  ...  \
0                0             0           0            0           0  ...   
1                0             0           0            0           0  ...   
2                0             0           0            0           0  ...   
3                0             0           0            0           0  ...   
4                0             0           0            0           0  ...   
...            ...           ...         ...          ...         ...  ...   
6497             0             0           0            0           0  ...   
6498             0             0           0            0           0  ...   
6499             0             0           0            0           0  ...   
6500             0             0           0            0           0  ...   
6501             0             0           0            0           0  ...   

      brand_Renault  brand_Skoda  brand_Tata  brand_Toyota  brand_Volkswagen  \
0                 0            0           0             0                 0   
1                 0            0           1             0                 0   
2                 0            0           1             0                 0   
3                 0            0           0             0                 1   
4                 0            0           0             0                 0   
...             ...          ...         ...           ...               ...   
6497              0            0           0             0                 0   
6498              0            0           0             0                 0   
6499              0            0           0             0                 0   
6500              0            0           0             0                 0   
6501              0            0           0             0                 0   

      brand_Volvo  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  
0               0         0            0         0            1  
1               0         0            1         0            0  
2               0         0            1         0            0  
3               0         0            1         0            0  
4               0         0            1         0            0  
...           ...       ...          ...       ...          ...  
6497            0         0            1         0            0  
6498            0         0            0         0            1  
6499            0         0            0         0            1  
6500            0         0            0         0            1  
6501            0         0            0         0            1  

[6502 rows x 35 columns]

# Get dummies Trap- Used to reduce multi colinearity between features.

In [39]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train,X_test,y_train,y_test=train_test_split(cars.iloc[:,0:4:2],cars.iloc[:,-1],test_size=0.2)

In [40]:
pd.DataFrame(ohe.fit_transform(X_train),columns=ohe.get_feature_names_out())

brand_Ashok  brand_Audi  brand_BMW  brand_Chevrolet  brand_Daewoo  \
0             0.0         0.0        0.0              0.0           0.0   
1             0.0         0.0        0.0              0.0           0.0   
2             0.0         0.0        0.0              0.0           0.0   
3             0.0         0.0        0.0              0.0           0.0   
4             0.0         0.0        0.0              0.0           0.0   
...           ...         ...        ...              ...           ...   
6497          0.0         0.0        0.0              0.0           0.0   
6498          0.0         0.0        0.0              0.0           0.0   
6499          0.0         0.0        0.0              0.0           0.0   
6500          0.0         0.0        0.0              0.0           0.0   
6501          0.0         0.0        0.0              0.0           0.0   

      brand_Datsun  brand_Fiat  brand_Force  brand_Ford  brand_Honda  ...  \
0              0.0         0.0          0.0         0.0          0.0  ...   
1              0.0         0.0          0.0         0.0          0.0  ...   
2              0.0         0.0          0.0         0.0          0.0  ...   
3              0.0         0.0          0.0         0.0          1.0  ...   
4              0.0         0.0          0.0         0.0          0.0  ...   
...            ...         ...          ...         ...          ...  ...   
6497           0.0         0.0          0.0         0.0          0.0  ...   
6498           0.0         0.0          0.0         0.0          0.0  ...   
6499           0.0         0.0          0.0         0.0          0.0  ...   
6500           0.0         0.0          0.0         0.0          0.0  ...   
6501           0.0         0.0          0.0         0.0          0.0  ...   

      brand_Nissan  brand_Renault  brand_Skoda  brand_Tata  brand_Toyota  \
0              0.0            0.0          0.0         0.0           0.0   
1              0.0            0.0          0.0         1.0           0.0   
2              0.0            0.0          0.0         0.0           0.0   
3              0.0            0.0          0.0         0.0           0.0   
4              0.0            0.0          0.0         0.0           1.0   
...            ...            ...          ...         ...           ...   
6497           0.0            0.0          0.0         0.0           0.0   
6498           0.0            0.0          0.0         0.0           0.0   
6499           0.0            0.0          0.0         0.0           0.0   
6500           0.0            0.0          0.0         0.0           1.0   
6501           0.0            0.0          0.0         0.0           0.0   

      brand_Volkswagen  brand_Volvo  fuel_Diesel  fuel_LPG  fuel_Petrol  
0                  0.0          0.0          0.0       0.0          1.0  
1                  0.0          0.0          1.0       0.0          0.0  
2                  0.0          0.0          1.0       0.0          0.0  
3                  0.0          0.0          0.0       0.0          1.0  
4                  0.0          0.0          0.0       0.0          1.0  
...                ...          ...          ...       ...          ...  
6497               0.0          0.0          0.0       0.0          1.0  
6498               0.0          0.0          1.0       0.0          0.0  
6499               0.0          0.0          1.0       0.0          0.0  
6500               0.0          0.0          0.0       0.0          1.0  
6501               0.0          0.0          1.0       0.0          0.0  

[6502 rows x 32 columns]

In [41]:
# Handeling rare value
X_train['brand'].value_counts()

brand
Maruti           1952
Hyundai          1141
Mahindra          619
Tata              590
Toyota            389
Honda             367
Ford              313
Renault           191
Chevrolet         181
Volkswagen        147
BMW               106
Skoda              84
Nissan             70
Jaguar             57
Volvo              51
Datsun             49
Mercedes-Benz      40
Fiat               38
Audi               32
Jeep               24
Lexus              23
Mitsubishi         10
Force               6
Isuzu               5
Ambassador          4
Land                4
Daewoo              3
Kia                 3
MG                  2
Ashok               1
Name: count, dtype: int64

In [42]:
# Use Fequency
ohe=OneHotEncoder(sparse_output=False,min_frequency=100)

In [43]:
ohe.fit_transform(X_train).shape

(6502, 15)

In [44]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Mahindra', 'brand_Maruti', 'brand_Renault',
       'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_infrequent_sklearn', 'fuel_Diesel', 'fuel_Petrol',
       'fuel_infrequent_sklearn'], dtype=object)

In [45]:
# Max categories
ohe= OneHotEncoder(sparse_output=False,max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 19)

In [46]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [47]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1.]])

In [48]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variable for a multi-class classification problem
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized labels:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)


Binarized labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']


In [49]:
from sklearn.preprocessing import MultiLabelBinarizer

# Example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the data to binary matrix format
Y = mlb.fit_transform(y)

print("Binary matrix:\n", Y)
print("Class labels:", mlb.classes_)

# Inverse transform to recover original labels
y_inv = mlb.inverse_transform(Y)
print("Inverse transformed labels:", y_inv)


Binary matrix:
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Inverse transformed labels: [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]


In [56]:
from sklearn.preprocessing import LabelBinarizer
y_pred=['cat','dog','monkey','lion']

lb=LabelBinarizer()

y_label=lb.fit_transform(y_pred)
print(y_label)

original = lb.inverse_transform(y_label)
print(original)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
['cat' 'dog' 'monkey' 'lion']


In [57]:
from sklearn.preprocessing import MultiLabelBinarizer

y=[('sun','moon'),('cat','dog'),('sameer','ameer')]

mlb=MultiLabelBinarizer()

ypres=mlb.fit_transform(y)
print(ypres)
print(mlb.classes_)
print(mlb.inverse_transform(ypres))

[[0 0 0 1 0 1]
 [0 1 1 0 0 0]
 [1 0 0 0 1 0]]
['ameer' 'cat' 'dog' 'moon' 'sameer' 'sun']
[('moon', 'sun'), ('cat', 'dog'), ('ameer', 'sameer')]


In [ ]:
! pip install category_encoders

In [64]:
import pandas as pd
import numpy as np
import category_encoders as ce
# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)

df.head()



Age       State    Education    Package
0  54.0  Tamil Nadu  High School  40.612049
1  49.0       Delhi           PG  56.921076
2   NaN   Telangana  High School  34.360550
3  54.0       Delhi           PG  78.887278
4  33.0       Delhi           PG  41.137241

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [66]:
X_train['State'].value_counts()

State
Delhi          18
Tamil Nadu     17
Telangana      17
Maharashtra    14
Karnataka      14
Name: count, dtype: int64

In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import sklearn

In [69]:
class CountEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, columns=None):
        self.columns = columns
        self.count_map = {}

    def fit(self, X, y=None):
        if self.columns is None:
            self.columns = X.columns
        for col in self.columns:
            self.count_map[col] = X[col].value_counts().to_dict()
        return self

    def transform(self, X):
        X = X.copy()
        for col in self.columns:
            X[col] = X[col].map(self.count_map[col]).fillna(0)
        return X

In [74]:
preprocessor=ColumnTransformer(
    transformers=[
        ('age_misssing',SimpleImputer(strategy='mean'),['Age']),
        ('cat_state',CountEncoder(),['State']),
        ('educational_ordinal',OrdinalEncoder(),['Education'])
    ]
)

In [75]:
sklearn.set_config(transform_output='pandas')

In [76]:
preprocessor.fit_transform(X_train)

age_misssing__Age  cat_state__State  educational_ordinal__Education
55          38.666667                17                             0.0
88          42.000000                14                             1.0
26          38.666667                14                             1.0
42          39.000000                18                             1.0
69          33.000000                18                             0.0
..                ...               ...                             ...
60          45.000000                17                             0.0
71          44.000000                17                             0.0
14          50.000000                14                             2.0
92          31.000000                14                             2.0
51          23.000000                17                             0.0

[80 rows x 3 columns]